Mr\StartBundle\Entity\MrContinent:
  type: entity
  table: mr_continent
  gedmo:
    translation:
      locale: locale
# using specific personal translation class:
#     entity: Translatable\Fixture\CategoryTranslation
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    name:
      type: string
      length: 250
      fixed: false
      nullable: false
      gedmo:
        - translatable
  lifecycleCallbacks: {  }
