Mr\StartBundle\Entity\MrDiploma:
  type: entity
  table: mr_diploma
  gedmo:
    loggable: 
      #logEntryClass: MrDiplomaLog
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    name:
      type: string
      length: 250
      fixed: false
      nullable: false
      unique: true
      gedmo:
        - sluggable
        - Versioned
    slug:
      type: string
      length: 128
      gedmo:
        slug:
          separator: -
          style: default
    twitterhash:
      type: text
      nullable: true
    created_at:
      type: date
      gedmo:
        timestampable:
          on: create
    updated_at:
      type: datetime
      gedmo:
        timestampable:
          on: update
  manyToOne:
    type:
      targetEntity: MrDiplomaType
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        type_id:
          referencedColumnName: id
      orphanRemoval: false
  manyToMany:
    areas:
      targetEntity: MrArea
      inversedBy: diploma_id
      joinColumns:
        diploma_id:
          referencedColumnName: id
      inverseJoinColumns:
        area_id:
          referencedColumnName: id
  lifecycleCallbacks: {  }
