Mr\StartBundle\Entity\MrSynonym:
  type: entity
  table: mr_synonym
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    mr_object_id:
      type: integer
    mr_object_name:
      type: string
      length: 20
    synonym:
      type: integer
    mr_to_partner_id:
      type: integer
    created_at:
      type: date
      gedmo:
        timestampable:
          on: create
    updated_at:
      type: datetime
      gedmo:
        timestampable:
          on: update
      orphanRemoval: false
  oneToOne:
    city:
      targetEntity: MrToPartner
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        mr_to_partner_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
