Mr\StartBundle\Entity\MrUserStep:
  type: entity
  table: mr_user_step
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    object_id:
      type: integer
    object_type:
      type: string
      length: 20
    start_at:
      type: date
    end_at:
      type: date
    comment:
      type: text
    liked:
      type: boolean
    current:
      type: boolean
    created_at:
      type: date
      gedmo:
        timestampable:
          on: create
    updated_at:
      type: datetime
      gedmo:
        timestampable:
          on: update
  manyToMany:
    stepacquaintance:
      targetEntity: MrUser
      inversedBy: stepacquaintance
      joinTable:
        name: mr_user_acquaintance
        joinColumns:
          userstep_id:
            referencedColumnName: id
        inverseJoinColumns:
          user_id:
            referencedColumnName: id
  manyToOne:
    user:
      nullable: false
      targetEntity: MrUser
      cascade: {  }
      joinColumns:
        user_id:
          referencedColumnName: id
      orphanRemoval: false
  manyToOne:
    location:
      nullable: true
      targetEntity: MrLocation
      cascade: {  }
      joinColumns:
        location_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
