MrCountry:
  type: entity
  table: mr_country
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    name:
      type: string
      length: 250
      fixed: false
      nullable: false
    code:
      type: string
      length: 5
      fixed: false
      nullable: false
    updatedAt:
      type: datetime
      nullable: false
      column: updated_at
    createdAt:
      type: datetime
      nullable: false
      column: created_at
  oneToOne:
    continent:
      targetEntity: MrContinent
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        continent_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
