MrGroup:
  type: entity
  table: mr_group
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    name:
      type: string
      length: 255
      fixed: false
      nullable: false
    roles:
      type: text
      nullable: false
  lifecycleCallbacks: {  }
