Mr\StartBundle\Entity\MrLocation:
  type: entity
  table: mr_location
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    childofId:
      type: integer
      unsigned: false
      nullable: true
      column: childof_id
    type:
      type: integer
      unsigned: false
      nullable: false
      column: step_type
    name:
      type: string
      length: 250
      fixed: false
      nullable: false
    adress:
      type: string
      length: 250
      fixed: false
      nullable: false
    zipCode:
      type: boolean
      nullable: false
      column: zip_code
  oneToOne:
    city:
      targetEntity: MrCity
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        city_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
