<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class MrStartBundleEntityMrUserStepProxy extends \Mr\StartBundle\Entity\MrUserStep implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setUser(\Mr\StartBundle\Entity\MrUser $user)
    {
        $this->__load();
        return parent::setUser($user);
    }

    public function getUser()
    {
        $this->__load();
        return parent::getUser();
    }

    public function setLocation(\Mr\StartBundle\Entity\MrLocation $location)
    {
        $this->__load();
        return parent::setLocation($location);
    }

    public function getLocation()
    {
        $this->__load();
        return parent::getLocation();
    }

    public function setDate($date)
    {
        $this->__load();
        return parent::setDate($date);
    }

    public function getDate()
    {
        $this->__load();
        return parent::getDate();
    }

    public function setComment($comment)
    {
        $this->__load();
        return parent::setComment($comment);
    }

    public function getComment()
    {
        $this->__load();
        return parent::getComment();
    }

    public function setObjectId($objectId)
    {
        $this->__load();
        return parent::setObjectId($objectId);
    }

    public function getObjectId()
    {
        $this->__load();
        return parent::getObjectId();
    }

    public function setObjectType($objectType)
    {
        $this->__load();
        return parent::setObjectType($objectType);
    }

    public function getObjectType()
    {
        $this->__load();
        return parent::getObjectType();
    }

    public function addStepacquaintance(\Mr\StartBundle\Entity\MrUser $stepacquaintance)
    {
        $this->__load();
        return parent::addStepacquaintance($stepacquaintance);
    }

    public function getStepacquaintance()
    {
        $this->__load();
        return parent::getStepacquaintance();
    }

    public function setCreatedAt($createdAt)
    {
        $this->__load();
        return parent::setCreatedAt($createdAt);
    }

    public function getCreatedAt()
    {
        $this->__load();
        return parent::getCreatedAt();
    }

    public function setUpdatedAt($updatedAt)
    {
        $this->__load();
        return parent::setUpdatedAt($updatedAt);
    }

    public function getUpdatedAt()
    {
        $this->__load();
        return parent::getUpdatedAt();
    }

    public function setStartAt($startAt)
    {
        $this->__load();
        return parent::setStartAt($startAt);
    }

    public function getStartAt()
    {
        $this->__load();
        return parent::getStartAt();
    }

    public function setEndAt($endAt)
    {
        $this->__load();
        return parent::setEndAt($endAt);
    }

    public function getEndAt()
    {
        $this->__load();
        return parent::getEndAt();
    }

    public function setLiked($liked)
    {
        $this->__load();
        return parent::setLiked($liked);
    }

    public function getLiked()
    {
        $this->__load();
        return parent::getLiked();
    }

    public function setCurrent($current)
    {
        $this->__load();
        return parent::setCurrent($current);
    }

    public function getCurrent()
    {
        $this->__load();
        return parent::getCurrent();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'object_id', 'object_type', 'start_at', 'end_at', 'comment', 'liked', 'current', 'created_at', 'updated_at', 'location', 'stepacquaintance');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}